### ISSUE TITLE
Add .pre-comit-config.yaml settings to README

### ISSUE THREAD

**Issue by Roald87** [pcdshub/pre-commit-hooks#16]
I wrote a small post regarding using pre-commits with TwinCAT files. I used your pre-commit as and example as well. <https://cookncode.com/twincat/2022/04/14/pre-commit.html>

Thanks for making it available!

Maybe an idea to add the `.pre-commit-config.yaml` files to the `README.md`? Then more experienced people can immediately copy paste the relevant stuff. For example how it's done here: <https://github.com/pre-commit/pre-commit-hooks>.

**Comment by klauer** [comment]
Nice article, @Roald87 - and thanks for mentioning us. 👍 

We definitely should include more information on each of the hooks + copy-paste-able examples here.

**Comment by ZLLentz** [comment]
closed by #24
